version: '3.7'
services:
  mongodb_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: '<change-me>'
      MONGO_INITDB_ROOT_PASSWORD: '<change-me>'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db